{
 "title": "Ballerina Http Metrics Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Http Metrics Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Http Response Time by Instance",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(http_response_time_seconds)by (instance)"
      }
     ]
    },
    {
     "title": "Average Http Response Time by Service",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(http_response_time_seconds)by(service)"
      }
     ]
    },
    {
     "title": "Average Http Response Time by Url",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(http_response_time_seconds)by(http_url)"
      }
     ]
    },
    {
     "title": "Average Http Response Time by Resource",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(http_response_time_seconds)by(resource)"
      }
     ]
    },
    {
     "title": "Average Http Response Time by Method",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(http_response_time_seconds)by (http_method)"
      }
     ]
    },
    {
     "title": "Average Http Response Time by Protocol",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(http_response_time_seconds)by(protocol)"
      }
     ]
    }
   ]
  },
  {
   "title": "Ballerina Http Client Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Ballerina Http Client Response Time by Action",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(ballerina_http:HttpCachingClient_response_time_seconds)by (action)"
      }
     ]
    },
    {
     "title": "Average Ballerina Http Client Response Time by Instance",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(ballerina_http:HttpCachingClient_response_time_seconds)by (instance)"
      }
     ]
    },
    {
     "title": "Average Ballerina Http Client Response Time by Method",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(ballerina_http:HttpCachingClient_response_time_seconds)by (http_method)"
      }
     ]
    },
    {
     "title": "Average Ballerina Http Client Response Time by Url",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(ballerina_http:HttpCachingClient_response_time_seconds)by (http_url)"
      }
     ]
    },
    {
     "title": "Average Ballerina Http Client Response Time by Peer_Hostname",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(ballerina_http:HttpCachingClient_response_time_seconds)by (peer_hostname)"
      }
     ]
    },
    {
     "title": "Average Ballerina Http Client Response Time by Peer_Port",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "s", "label": "Time(s)" }
     ],
     "targets": [
      {
       "expr": "avg(ballerina_http:HttpCachingClient_response_time_seconds)by (peer_port)"
      }
     ]
    }
   ]
  }
 ]
}