{
 "title": "Ballerina SQL Metrics Overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Ballerina SQL Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average SQL Response Time by Actions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "Time(s)" }
   ],
   "targets": [
    {
     "expr": "avg(ballerina_sql:CallerActions_response_time_seconds)by(action)"
    }
   ]
  },
  {
   "title": "Average SQL Response Time by Instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s", "label": "Time(s)" }
   ],
   "targets": [
    {
     "expr": "avg(ballerina_sql:CallerActions_response_time_seconds)by(instance)"
    }
   ]
  },
  {
   "title": "Average SQL Response Time by Database Statement",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s", "label": "Time(s)" }
   ],
   "targets": [
    {
     "expr": "avg(ballerina_sql:CallerActions_response_time_seconds)by(db_statement)"
    }
   ]
  }
 ]
}