{
 "title": "Ballerina SQL Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" },
   {
    "name": "dbaction",
    "label": "db-action",
    "query": "label_values(ballerina_sql:CallerActions_requests_total, action)"
   },
   {
    "name": "dbstatement",
    "label": "db-statement",
    "query": "label_values(ballerina_sql:CallerActions_requests_total,db_statement)"
   }
  ]
 },
 "panels": [
  {
   "title": "Ballerina SQL Throughput",
   "type": "graph",
   "description": "This is the SQL Response Time throughput",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Time(s)" }
   ],
   "targets": [
    {
     "expr": "rate(ballerina_sql:CallerActions_requests_total{instance=~\"$instance\",action=~\"$dbaction\",db_statement=~\"$dbstatement\"}[1m])"
    },
    {
     "expr": "rate(ballerina_sql:CallerActions_requests_total{instance=~\"$instance\",action=~\"$dbaction\",db_statement=~\"$dbstatement\"}[15m])",
     "legendFormat": "{{instance}}--{{action}}--{{job}}--{{db_statement}}--15m"
    }
   ]
  },
  {
   "title": "Ballerina SQL Response Time",
   "type": "graph",
   "description": "This is the SQL Response Time",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "Time(s)" }
   ],
   "targets": [
    {
     "expr": "ballerina_sql:CallerActions_response_time_seconds{action=~\"$dbaction\",instance=~\"$instance\",db_statement=~\"$dbstatement\"}",
     "legendFormat": "{{instance}}--{{action}}--{{db_statement}}--{{quantile}}"
    }
   ]
  },
  {
   "title": "Ballerina SQL Response Time Statistics",
   "type": "graph",
   "description": "Average of the SQL Response Time",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s", "label": "Time(s)" }
   ],
   "targets": [
    {
     "expr": "avg(ballerina_sql:CallerActions_response_time_seconds{action=~\"$dbaction\",instance=~\"$instance\",db_statement=~\"$dbstatement\"})without(quantile)",
     "legendFormat": "{{instance}}--{{action}}--{{db_statement}}"
    }
   ]
  }
 ]
}